name: Deploy

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cloudflare/wrangler-action@v2
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: pages deploy ./ --project-name=reading-tech-folk --branch=${{ github.ref_name }}
